Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -87,17 +87,17 @@
 			echo -e "\033[0;34m  #BY: 🔥⚡️⚡️ Sithum Batrow 🇱🇰 ⚡️⚡️🔥         \E[0m"
 			echo ""
 			IP=$(wget -qO- ipv4.icanhazip.com)
-			echo -ne "\033[1;32mเช็คความถูกต้อง IP เพิ่อดำเนินการต่อ: \033[1;37m"
+			echo -ne "\033[1;32mTO CONTINUE CONFIRM YOUR IP: \033[1;37m"
 			read -e -i $IP ipdovps
 			[[ -z "$ipdovps" ]] && {
 				echo -e "\n\033[1;31mIP invalido\033[1;32m"
 				echo ""
 				read -p "Enter your IP: " IP
 			}
-			echo -e "\n\033[1;33mต้องการใช้พอร์ทได เพื่อติดตั้ง SQUID \033[1;31m?"
-			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mตั้งค่าพอร์ท \033[1;33mตัวอย่าง: \033[1;37m8080"
+			echo -e "\n\033[1;33mWHICH PORTS DO YOU WANT TO USE IN THE SQUID \033[1;31m?"
+			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mSET THE PORTS IN SEQUENCE \033[1;33mEX: \033[1;37m80 8080"
 			echo ""
-			echo -ne "\033[1;32mใส่พอร์ที่ต้องการใช้งาน\033[1;37m: "
+			echo -ne "\033[1;32mINFORM THE PORTS\033[1;37m: "
 			read portass
 			[[ -z "$portass" ]] && {
 				echo -e "\n\033[1;31mInvalid port!"
@@ -108,11 +108,11 @@
 				verif_ptrs $porta
 			done
 			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
-				echo -e "\n\033[1;32mกำลังติดตั้ง SQUID PROXY\033[0m\n"
+				echo -e "\n\033[1;32mINSTALLING SQUID PROXY\033[0m\n"
 				fun_bar 'apt update -y' "apt install squid3 -y"
 			} || {
-				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID เวอร์ชั่น 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID เวอร์ชั่น 3.5.X\033[0m\n"
-				read -p "$(echo -e "\033[1;32mREPORT AN OPTION \033[1;37m: ")" -e -i 2 opc
+				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
+				read -p "$(echo -e "\033[1;32mREPORT AN OPTION \033[1;37m: ")" -e -i 1 opc
 				[[ -z "$opc" ]] && {
 					echo -e "\n\033[1;31mOption invalid!"
 					sleep 2
@@ -125,7 +125,7 @@
 						fun_conexao
 					}
 				}
-				echo -e "\n\033[1;32mกำลังติดตั้ง SQUID PROXY\033[0m\n"
+				echo -e "\n\033[1;32mINSTALLING SQUID PROXY\033[0m\n"
 				fun_bar 'apt update -y' "instsqd $opc"
 			}
 			if [[ -d "/etc/squid/" ]]; then
@@ -135,7 +135,7 @@
 				var_sqd="/etc/squid3/squid.conf"
 				var_pay="/etc/squid3/payload.txt"
 			else
-				echo -e "\n\033[1;33m[\033[1;31mผิดพลาด\033[1;33m]\033[1;37m: \033[1;33mO แพ็คเกจ SQUID PROXYเสียหาย\033[0m"
+				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO CORRUPTED SQUID PROXY\033[0m"
 				sleep 2
 				fun_conexao
 			fi
@@ -152,7 +152,6 @@
 				acl url4 dstdomain -i /SSHPLUS?
 				acl payload url_regex -i "$var_pay"
 				acl all src 0.0.0.0/0
-
 				http_access allow url1
 				http_access allow url2
 				http_access allow url3
@@ -185,31 +184,31 @@
 					service squid3 restart
 				}
 			}
-			echo -e "\n\033[1;32mกำหนดค่า SQUID PROXY\033[0m"
+			echo -e "\n\033[1;32mCONFIGURING SQUID PROXY\033[0m"
 			echo ""
 			fun_bar 'sqd_conf'
-			echo -e "\n\033[1;32mติดตั้ง SQUID PROXY สำเร็จ!\033[0m"
+			echo -e "\n\033[1;32mSQUID INSTALLED SUCCESSFULLY!\033[0m"
 			sleep 2.5s
 			fun_conexao
 		fi
 	}
 
 	addpt_sqd() {
-		echo -e "\E[44;1;37m            เพิ่ม พอร์ท SQUID        \E[0m"
+		echo -e "\E[44;1;37m            ADD PORTS TO SQUID        \E[0m"
 		echo -e "\033[0;34m  #BY: 🔥⚡️⚡️ Sithum Batrow 🇱🇰 ⚡️⚡️🔥         \E[0m"
-		echo -e "\n\033[1;33mพอร์ทที่ใช้งาน: \033[1;32m$sqdp\n"
+		echo -e "\n\033[1;33mPORTS IN USE: \033[1;32m$sqdp\n"
 		if [[ -f "/etc/squid/squid.conf" ]]; then
 			var_sqd="/etc/squid/squid.conf"
 		elif [[ -f "/etc/squid3/squid.conf" ]]; then
 			var_sqd="/etc/squid3/squid.conf"
 		else
-			echo -e "\n\033[1;31mSQUID ไม่ได้ติดตั้ง!\033[0m"
+			echo -e "\n\033[1;31mSQUID IS NOT INSTALLED!\033[0m"
 			echo -e "\n\033[1;31mReturning ...\033[0m"
 			sleep 2
 			clear
 			fun_squid
 		fi
-		echo -ne "\033[1;32mต้องการเพิ่มพอร์ดได \033[1;33m?\033[1;37m "
+		echo -ne "\033[1;32mWHICH PORTS YOU WANT TO ADD \033[1;33m?\033[1;37m "
 		read pt
 		[[ -z "$pt" ]] && {
 			echo -e "\n\033[1;31mInvalid ports!"
@@ -218,14 +217,14 @@
 			fun_conexao
 		}
 		verif_ptrs $pt
-		echo -e "\n\033[1;32mกำลังเพิ่มพอร์ท SQUID!"
+		echo -e "\n\033[1;32mADDING PORTS TO SQUID!"
 		echo ""
 		sed -i "s/#Portas/#Portas\nhttp_port $pt/g" $var_sqd
 		fun_bar 'sleep 2'
-		echo -e "\n\033[1;32mกำลังรีสตาร์ท SQUID!"
+		echo -e "\n\033[1;32mRESTARTING SQUID!"
 		echo ""
 		fun_bar 'service squid restart' 'service squid3 restart'
-		echo -e "\n\033[1;32mเพิ่มพอร์ท สำเร็จ!"
+		echo -e "\n\033[1;32mSUCCESSFULLY ADDED PORTS!"
 		sleep 3
 		clear
 		fun_squid
@@ -276,7 +275,7 @@
 
 	fun_squid() {
 		[[ "$(netstat -nplt | grep -c 'squid')" = "0" ]] && inst_sqd
-		echo -e "\E[44;1;37m          การจัดการ SQUID PROXY           \E[0m"
+		echo -e "\E[44;1;37m          MANAGE SQUID PROXY           \E[0m"
 		[[ "$(netstat -nplt | grep -c 'squid')" != "0" ]] && {
 			sqdp=$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)
 			echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sqdp"
@@ -285,9 +284,9 @@
 			VarSqdOn="INSTALL SQUID PROXY"
 		}
 		echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33m$VarSqdOn \033[1;31m
-[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mเพื่มพอร์ท \033[1;31m
-[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mลบพอร์ท\033[1;31m
-[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ\033[0m"
+[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mADD PORTS \033[1;31m
+[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mREMOVE PORTS\033[1;31m
+[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mCOME BACK\033[0m"
 		echo ""
 		echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;31m?\033[1;37m "
 		read x
@@ -569,7 +568,7 @@
 					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
 					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-					cd /etc/stunnel && wget https://github.com/aritach/vps-new/blob/main/Install/stunnel.pem && cd $HOME
+					cd /etc/stunnel && wget https://github.com/sbatrow/DARKSSH-MANAGER/blob/main/Install/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
 				echo -e "\n\033[1;32mSTARTING SSL TUNNEL!\033[0m"
@@ -665,16 +664,16 @@
 				else
 					mult=$(echo -e "\033[1;31m○ ")
 				fi
-				echo -e "\E[44;1;37m          ตั้งค่า OPENVPN           \E[0m"
+				echo -e "\E[44;1;37m          GERENCIAR OPENVPN           \E[0m"
 				echo ""
 				echo -e "\033[1;33mPORTA\033[1;37m: \033[1;32m$opnp"
 				echo ""
-				echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mเปลี่ยนพอร์ท openvpn"
-				echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mถอนการติดตั้ง OPENVPN"
-				echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mสร้างไฟล์ดาวน์โหลด $ovpnweb"
-				echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mเปิด-ปิด การเชื่อมต่อได้หลายเครื่อง $mult"
-				echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mแก้ไขโฮส DNS"
-				echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mออกจากหน้านี้"
+				echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA"
+				echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER OPENVPN"
+				echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mOVPN VIA LINK $ovpnweb"
+				echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mMULTILOGIN OVPN $mult"
+				echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR HOST DNS"
+				echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR"
 				echo ""
 				echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
 				read option
@@ -755,11 +754,11 @@
 							rm -rf /usr/share/doc/openvpn*
 						}
 						echo ""
-						echo -e "\033[1;32mถอนติดตั้ง openvpn!\033[0m"
+						echo -e "\033[1;32mREMOVENDO O OPENVPN!\033[0m"
 						echo ""
 						fun_bar 'rmv_open'
 						echo ""
-						echo -e "\033[1;32mถอนติดตั้ง openvpn เรียบร้อยแล้ว!\033[0m"
+						echo -e "\033[1;32mOPENVPN REMOVIDO COM SUCESSO!\033[0m"
 						sleep 2
 						fun_conexao
 					} || {
@@ -789,7 +788,7 @@
 								done
 								tput cnorm
 							}
-							echo -ne "\033[1;31mกำลังปิด\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+							echo -ne "\033[1;31mDESATIVANDO\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 							helice
 							echo -e "\e[1DOk"
 						}
@@ -824,7 +823,7 @@
 								done
 								tput cnorm
 							}
-							echo -ne "\033[1;32mกำลังเปิด\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+							echo -ne "\033[1;32mATIVANDO\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 							helice
 							echo -e "\e[1DOk"
 						}
@@ -854,7 +853,7 @@
 								tput cnorm
 							}
 							echo ""
-							echo -ne "\033[1;31mกำลังปิด\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+							echo -ne "\033[1;31mBLOQUEANDO MULTILOGIN\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 							helice
 							echo -e "\e[1DOk"
 						}
@@ -882,7 +881,7 @@
 								tput cnorm
 							}
 							echo ""
-							echo -ne "\033[1;32mกำลังปิด\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+							echo -ne "\033[1;32mPERMITINDO MULTILOGIN\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 							helice
 							echo -e "\e[1DOk"
 						}
@@ -1002,15 +1001,15 @@
 			done
 		} || {
 			clear
-			echo -e "\E[44;1;37m              ติดตั้ง OPENVPN               \E[0m"
+			echo -e "\E[44;1;37m              INSTALADOR OPENVPN               \E[0m"
 			echo ""
-			echo -e "\033[1;33mใส่ค่าต่างๆ เพื่อทำการติดตั้ง"
+			echo -e "\033[1;33mRESPONDA AS QUESTOES PARA INICIAR A INSTALACAO"
 			echo ""
-			echo -ne "\033[1;32mยืนยันไอพี: \033[1;37m"
+			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
 			read -e -i $IP IP
 			[[ -z "$IP" ]] && {
 				echo ""
-				echo -e "\033[1;31mIP ไม่ถูกต้อง!"
+				echo -e "\033[1;31mIP invalido!"
 				sleep 3
 				fun_conexao
 			}
@@ -1018,15 +1017,15 @@
 			read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 443 porta
 			[[ -z "$porta" ]] && {
 				echo ""
-				echo -e "\033[1;31mPorta ไม่ถูกต้อง!"
+				echo -e "\033[1;31mPorta invalida!"
 				sleep 2
 				fun_conexao
 			}
 			echo ""
-			echo -e "\033[1;33mกำลังตรวจสอบ พอร์ท..."
+			echo -e "\033[1;33mVERIFICANDO PORTA..."
 			verif_ptrs $porta
 			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mDNS ของเซิฟเวอร์โดยตรง"
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mSistema"
 			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mGoogle (\033[1;32mRecomendado\033[1;33m)"
 			echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;33mOpenDNS"
 			echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;33mCloudflare"
@@ -1034,12 +1033,12 @@
 			echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;33mVerisign"
 			echo -e "\033[1;31m[\033[1;36m7\033[1;31m] \033[1;33mDNS Performace\033[0m"
 			echo ""
-			read -p "$(echo -e "\033[1;32mเลือก dns ? \033[1;37m")" -e -i 1 DNS
+			read -p "$(echo -e "\033[1;32mQUAL DNS DESEJA UTILIZAR? \033[1;37m")" -e -i 1 DNS
 			echo ""
 			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mUDP"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mTCP (\033[1;32mแนะนำ\033[1;33m)"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mTCP (\033[1;32mRecomendado\033[1;33m)"
 			echo ""
-			read -p "$(echo -e "\033[1;32mเลือก โปรโตคอล? \033[1;37m")" -e -i 2 resp
+			read -p "$(echo -e "\033[1;32mQUAL PROTOCOLO DESEJA UTILIZAR NO OPENVPN? \033[1;37m")" -e -i 2 resp
 			if [[ "$resp" = '1' ]]; then
 				PROTOCOL=udp
 			elif [[ "$resp" = '2' ]]; then
@@ -1049,14 +1048,14 @@
 			fi
 			echo ""
 			[[ "$OS" = 'debian' ]] && {
-				echo -e "\033[1;32mอัพเดท ระบบ"
+				echo -e "\033[1;32mATUALIZANDO O SISTEMA"
 				echo ""
 				fun_attos() {
 					apt-get update-y
 				}
 				fun_bar 'fun_attos'
 				echo ""
-				echo -e "\033[1;32mติดตั้ง โปรแกรมต่างๆ"
+				echo -e "\033[1;32mINSTALANDO DEPENDENCIAS"
 				echo ""
 				fun_instdep() {
 					apt-get install openvpn iptables openssl ca-certificates -y
@@ -1194,7 +1193,7 @@ exit 0' >$RCLOCAL
 					fi
 				fi
 			}
-			echo -e "\033[1;32mกำลังติดตั้ง OPENVPN  \033[1;31m(\033[1;33mอาจใช้เวลานาน!\033[1;31m)"
+			echo -e "\033[1;32mINSTALANDO O OPENVPN  \033[1;31m(\033[1;33mPODE DEMORAR!\033[1;31m)"
 			echo ""
 			fun_bar 'fun_dep > /dev/null 2>&1'
 			fun_ropen() {
@@ -1215,7 +1214,7 @@ exit 0' >$RCLOCAL
 				}
 			}
 			echo ""
-			echo -e "\033[1;32mรีสตาร์ท OPENVPN"
+			echo -e "\033[1;32mREINICIANDO O OPENVPN"
 			echo ""
 			fun_bar 'fun_ropen'
 			IP2=$(wget -4qO- "http://whatismyip.akamai.com/")
@@ -1224,16 +1223,15 @@ exit 0' >$RCLOCAL
 			fi
 			[[ $(grep -wc 'open.py' /etc/autostart) != '0' ]] && pt_proxy=$(grep -w 'open.py' /etc/autostart| cut -d' ' -f6) || pt_proxy=80
 			cat <<-EOF >/etc/openvpn/client-common.txt
-				# OVPN_ACCESS_SERVER_PROFILE=เซิฟไทย
+				# OVPN_ACCESS_SERVER_PROFILE=[SSHPLUS]
 				client
 				dev tun
 				proto $PROTOCOL
 				sndbuf 0
 				rcvbuf 0
-				port 443
-				remote 127.0.0.1
-				http-proxy $IP 8080
-				http-proxy-option CUSTOM-HEADER Host www.opensignal.com
+				remote 127.0.0.1 2222
+				route $IP 255.255.255.255 net_gateway
+				#MODO SLOWDNS, UTILIZE O APP OPENVPN PARA ANDROID, SELECIONE O TERMUX EM APLICAÇÕES PERMITIDAS
 				resolv-retry 5
 				nobind
 				persist-key
@@ -1250,7 +1248,7 @@ exit 0' >$RCLOCAL
 			EOF
 			# gerar client.ovpn
 			newclient "SSHPLUS"
-			[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mติดตั้ง OPENVPN เรียบร้อยแล้ว\033[0m" || echo -e "\n\033[1;31mติดตั้งไม่สำเร็จ !\033[0m"
+			[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN INSTALADO COM SUCESSO\033[0m" || echo -e "\n\033[1;31mERRO ! A INSTALACAO CORROMPEU\033[0m"
 		}
 		sed -i '$ i\echo 1 > /proc/sys/net/ipv4/ip_forward' /etc/rc.local
 		sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
@@ -1550,36 +1548,36 @@ exit 0' >$RCLOCAL
 	fun_openssh() {
 		clear
 		echo -e "\E[44;1;37m            OPENSSH             \E[0m\n"
-		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mเพิ่มพอร์ท\033[1;31m
-[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mลบพอร์ท\033[1;31m
-[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ\033[0m"
+		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mADICIONAR PORTA\033[1;31m
+[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER PORTA\033[1;31m
+[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
 		echo ""
-		echo -ne "\033[1;32mเลือกตาม เมนู \033[1;33m?\033[1;37m "
+		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
 		read resp
 		if [[ "$resp" = '1' ]]; then
 			clear
-			echo -e "\E[44;1;37m         เพิ่มพอร์ท ssh         \E[0m\n"
-			echo -ne "\033[1;32mเพิ่มพอร์ท \033[1;33m?\033[1;37m "
+			echo -e "\E[44;1;37m         ADICIONAR PORTA AO SSH         \E[0m\n"
+			echo -ne "\033[1;32mQUAL PORTA DESEJA ADICIONAR \033[1;33m?\033[1;37m "
 			read pt
 			[[ -z "$pt" ]] && {
-				echo -e "\n\033[1;31mพอร์ท ไม่ถูกต้อง!"
+				echo -e "\n\033[1;31mPorta invalida!"
 				sleep 3
 				fun_conexao
 			}
 			verif_ptrs $pt
-			echo -e "\n\033[1;32mเพิ่มพอร์ทไปยัง SSH\033[0m"
+			echo -e "\n\033[1;32mADICIONANDO PORTA AO SSH\033[0m"
 			echo ""
 			fun_addpssh() {
 				echo "Port $pt" >>/etc/ssh/sshd_config
 				service ssh restart
 			}
 			fun_bar 'fun_addpssh'
-			echo -e "\n\033[1;32mเพิ่มพอร์ท สำเร็จแล้ว\033[0m"
+			echo -e "\n\033[1;32mPORTA ADICIONADA COM SUCESSO\033[0m"
 			sleep 3
 			fun_conexao
 		elif [[ "$resp" = '2' ]]; then
 			clear
-			echo -e "\E[41;1;37m         ลบพอร์ท SSH         \E[0m"
+			echo -e "\E[41;1;37m         REMOVER PORTA DO SSH         \E[0m"
 			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mPORTA PADRAO \033[1;37m22 \033[1;33mCUIDADO !\033[0m"
 			echo -e "\n\033[1;33mPORTAS EM USO: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
 			echo -ne "\033[1;32mQUAL PORTA DESEJA REMOVER \033[1;33m?\033[1;37m "
@@ -1590,14 +1588,14 @@ exit 0' >$RCLOCAL
 				fun_conexao
 			}
 			[[ $(grep -wc "$pt" '/etc/ssh/sshd_config') != '0' ]] && {
-				echo -e "\n\033[1;32mลบพอร์ท SSH\033[0m"
+				echo -e "\n\033[1;32mREMOVENDO PORTA DO SSH\033[0m"
 				echo ""
 				fun_delpssh() {
 					sed -i "/Port $pt/d" /etc/ssh/sshd_config
 					service ssh restart
 				}
 				fun_bar 'fun_delpssh'
-				echo -e "\n\033[1;32mลบพอร์ท สำเร็จแล้ว\033[0m"
+				echo -e "\n\033[1;32mPORTA REMOVIDA COM SUCESSO\033[0m"
 				sleep 2
 				fun_conexao
 			} || {
@@ -1729,13 +1727,13 @@ exit 0' >$RCLOCAL
 [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
 [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
 [\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts8\033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
-[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mออกจากหน้านี้ \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo ""
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
 			echo ""
 			tput civis
-			echo -ne "\033[1;32mเลือกเมนู ที่ต้องการ \033[1;33m?\033[1;31m?\033[1;37m "
+			echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;31m?\033[1;37m "
 			read x
 			tput cnorm
 			clear
@@ -1768,7 +1766,7 @@ exit 0' >$RCLOCAL
 				menu
 				;;
 			0 | 00)
-				echo -e "\033[1;31mย้อนกลับออกไป...\033[0m"
+				echo -e "\033[1;31mSaindo...\033[0m"
 				sleep 2
 				clear
 				exit
